version: "3.7"

services:
  db:
    image: postgres:16
    container_name: db_name
    env_file:
      - .env
    volumes:
      - .postgres:/var/lib/postgresql/data


  redis:
    image: redis:7
    container_name: redis_app



  app:
    container_name: fastapi_app
    build:
      context: .
    env_file:
      - .env
    command: [ "python", "app/main.py" ]
    ports:
      - 8000:8080
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
      - db